# Generated by Django 3.2.20 on 2023-07-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
